#+TITLE: Call for Participants in Observational Study of Volition
#+CATEGORIES[]: ConSciEnt
#+DATE: 2021-04-13
#+SUMMARY: I am seeking volunteers to participate in an observational study of volition!

I am seeking volunteers to participate in an observational study of volition! As part of my [[{{< relref "../projects/vultolysis" >}}][Vultolysis]] project, I have been observing the choices I make in detail in various contexts and noticing some common threads among them. The primary goal of this study is to understand how choice manifests itself in others and whether the observations I've made in myself are universal.

At a high level, participants will be asked to set aside some time to do work that they normally do while self-monitoring and taking detailed notes of the choices they make. This will be my first study of this kind, though, so the main expectation of participants will be patience and a willingness to work with me as I learn the best ways to structure the tasks assigned. In particular, at this stage I'm not sure of what level of time commitment is needed, how many participants to shoot for, or the detailed particulars of the task. For the initial rounds of participants, I will share in more detail the kinds of notes and activities I'm looking for, but will be open to feedback and constraints and adjust accordingly over time. This is an exploratory study, future followups with more precise plans and specific hypotheses will follow when I'm ready for confirmation.

At this stage I am seeking breadth, so there are essentially no requirements to participate. I want people who are great at self-awareness and abysmal, people in highly cognitive jobs and highly physical, people with great executive function and terrible. If you even think you /might/ be interested, please reach out! You can contact me at [[mailto:shea@shealevy.com][shea@shealevy.com]] if you'd like to join, or with any questions you have.

* Other news
It's been some time since my last update. A few notes on what I've been up to:

- I have put the Texture of Understanding project on hold and have pivoted to the new [[{{< relref "../projects/vultolysis" >}}][Vultolysis]] project. I've learned a lot from what I've done so far, but I think digging into volition will have a much greater chance of the kind of payoff I'm looking for if I'm successful.
- I've made some minor adjustments to my website, including the [[{{< relref "../" >}}][ConSciEnt]] page. In particular, I have removed analytics for the time being.
- I am adjusting my level of publicity about my work, both to avoid spoiling potential research participants and to preserve potential future trade secrets for products I may build. As a result, I have removed my research notes from the page and will be limiting my newsletter to more infrequent high level news posts, public analysis of the field, and any findings I've intentionally decided to publicize.

Any feedback, or interested in participating? Find me at [[mailto:shea@shealevy.com][shea@shealevy.com]]!
