languageCode = "en-us"
baseURL = "https://shealevy.com/"
copyright = "© 2024 Shea Levy"
title = "Shea's site"
disqusShortname = "shealevy"
enableRobotsTXT = true

[permalinks]
  blog = "/blog/:year/:month/:day/:title/"

[params]
  dateFormat = "Monday, January 2, 2006"
  author = "Shea Levy"

[author]
  name = "Shea Levy"
