#+TITLE: Announcing ConSciEnt
#+DATE: 2020-08-03
#+DISQUS: t

Today I'm excited to go public with ConSciEnt, my research and development effort to gain a naturalistic exploitable understanding of consciousness!

# more

Those who know me well know that this is something I've been working toward in some form or other basically my entire life. Up until recently, though, that work has been relegated to sporadic efforts as a hobby or covering prerequisites. Now this is the main productive focus of my life[fn:job], a systematic daily effort to directly develop and apply knowledge of the nature and genesis of awareness.

What does that mean concretely? For now, I'm focusing on an observational exploration of the phenomenology of understanding. I'll be publishing raw research notes here on my blog several times a week, and updating my phenomenological glossary and project pages as I go[fn:bootstrap]. I also have a new weekly newsletter, which will include high level summaries of what I've been doing in that week, projected plans for what's coming next, and occasional reviews of articles and books of interest.

Want to learn more? Go check out the [[{{< relref "/conscient" >}}][ConSciEnt landing page]], which has further links to project-specific information. And don't forget to subscribe to the newsletter!

[fn:job] I do still have a paying job that I work hard and produce value at, but I am for now in maintenance mode with respect to my career progression and have more strict boundaries on the time spent there.

[fn:bootstrap] I've already populated the glossary and project pages with work done so far, though up until now I've not been as systematic as I plan to be
