#+TITLE: The Texture of Understanding
#+CATEGORIES[]: ConSciEnt
#+LASTMOD: 2020-08-14
#+DATE: 2020-08-01

What does it feel like to really /get/ something? How does that feeling develop and change as you learn? What role does that experience play in gaining and applying understanding to practical ends?

# more

This project is an observational exploration of these questions through the device of observing my experiences as I teach myself various mathematical and physical subjects. As I read, think, and work through problem sets, I am attending to what the subjective experience is like, with a particular focus on my feelings about some particular concept as I progress from complete ignorance to deep grokking. I am starting in a mode of almost unconstrained watching, but as I uncover structure I plan to become more experimental to dig into phenomena of interest.

* Curriculum

With the aid of [[https://mark-moon.github.io/][Mark Moon]], I'm developing and slowly working through a curriculum to get me from my current knowledge to a working understanding of the theory of general relativity and the standard model of particle physics. Though I am interested in those subjects for their own sake, this is primarily intended as a way to be able to predictably encounter subjects I don't understand and systematically gain understanding of them.

1. Despite already knowing linear algebra, I am starting with [[http://linear.axler.net/][Linear Algebra Done Right]] to get back into a habit of academic learning, start building up the skill of observing myself as I learn, and refresh myself in preparation for the linear algebra-heavy subject of quantum mechanics.

* Notable Observations

** Negative salience

When I come across a topic I don't understand, there's an immediately salient feeling of "not getting it" that I can then explore to figure out what I'm missing and where I need to work. I suspect one major role of experience in understanding is directing attention to its lack, an idea dovetailing with developments in other fields such as the [[https://en.wikipedia.org/wiki/Predictive_coding][predictive processing model of cognition]].

In some cases, the feeling of "not getting" something seems to be related to lack of (confident) knowledge of how concretely to proceed/address some problem. Is understanding fundamentally tied to a particular practical orientation?

** Mental operations

I am noticing an abundance of interesting different experiences when performing the various mental operations, particularly symbolic manipulations required to solve exercises and walking through proofs. I hope to catalogue these and see if any interesting patterns fall out, especially as I make progress and the size of the "primitive" operations I know how to perform grows. So far the main insight has been that, while I don't strongly visualize when I'm thinking, there is a definite spatial component to how symbolic manipulations feel, and a distinct modality for verbal thought.

When I'm reading through new material, I sometimes perform little "snippets" of these operations related to what I'm reading, seemingly involuntarily. How does that relate to a growing understanding?

Does fluency in these techniques rise directly with understanding? Is that (part of) what understanding /is/?
