#+TITLE: Vultolysis
#+CATEGORIES[]: ConSciEnt
#+DATE: 2021-04-13

Volition is an essential aspect of human existence. We're all familiar with the experience of evaluating what we observe, what we know, and what we want and intentionally choosing some action or other accordingly. Monumental and trivial, cognitive and physical, free will is everywhere in daily living.

But can we say anything more about volition itself? Can choices be analyzed into basic kinds of choices we can directly make, with more complex choices being built out of those? What attributes do choices have, can one choice be more "intense" than another? In detail, how do we experience choices? What are the dynamics of the interplay between perception, automatized thought/action, and chosen thought/action? Do choices happen at one moment in time, or are they actively sustained for an extended duration? How do choices relate to the physiological activity leading to and executing them? Do the answer to any of these questions vary for different people or different activities?

*Vultolysis* is a project to find the answers to these questions. The goal is to analyze, understand, and ultimately measure volitional action across the whole human spectrum.

* Natural observation
As a starting point, I am observing my own choices at play in the course of my other activities. When I think through a programming problem, or put away the dishes, what choices do I make? What are they based on? What do they feel like? Where in the body do I experience them? When am I choosing vs acting on automatic?

I have reached a point in my observations where comparing my experiences with those of others could be very valuable. I am [[{{< relref "../newsletter-issues/volition-study" >}}][seeking participants]] to study this futher.
