#+TITLE: 2020-08-14 Weekly Review
#+DATE: 2020-08-14
#+CATEGORIES[]: ConSciEnt
#+SUMMARY: Weekly review 2020-08-08 through 2020-08-14
* Observations
+ Ordiation is common when reading to understand
+ Ordiation is often incomplete/vague
+ Definite difference between blank observation, reading without it "clicking" (but also without confusion!), and reading and getting it
  + Possibly strush? A few times felt the pressure in the xyphoid
+ Significant effort expenditure to do this observation
+ Sought motivation for material I got but didn't know how to use
+ Notable distinction between thinking about projection in terms of an informal/natural understanding vs the formal mathematical definition
  + Building up a correspondence/relationship
* Speculations
+ Am I building up some kind of "context" as I go? An accumulated state/perspective/stance?
+ Ordiation as possibly some of the implicit context "leaking" out, or possibly something that needs attention to ensure it's correct?
+ Being able to act on knowledge part of holding the context together?
+ Perceptual expertise seems at work
+ Possible relationship to global workspace theory?
* Keep in mind
+ Probe the context!
+ Focus on the positive aspects denoting understanding, relationship to the context.
+ Back to the qualities of the experiences
  + What is the "satisfaction" feeling?
+ Border between ordiation and explicit processing
+ Look out for bigger time horizon understanding changes
+ Voluntariness of ordiation? Does it "just happen"?
+ Does ordiation ever happen "in the background"?
+ Look for multiple perspectives in play, their relationships
* Action items
+ Predictive processing
+ Workspace theory
+ Non-math examples
  + Personal life
  + Other intellectual things
  + Kelly
+ Ecological perception
  + Affordances
  + Ball catching
+ Find a subject to check in on longitudinally
  + Describe current understanding, how it grows?
* Raw brainstorm
Ordiation is key theme, plus its relationship to having a "grasp" on the subject.

Secondary theme of different perspectives/notions for thinking about a thing (formal vs informal in the case of projection), and the correspondence/relationship between those.

Found myself seeking motivation for material I "got" but didn't care about... Action holds the grasp together?

Observing myself learning requires a significant level of effort/attention... Or perhaps the other things I do don't require much at all?

Signs of perceptual expertise... Would I have noticed the fleeting ordiations that were barely coherent? Will I notice them further later?

Need to read up on predictive processing!

Is "reading to understand" setting up the context for what follows?

Checking that terms are well defined, steps make sense.

Need to pay more attention to the qualities of these experiences! Where are they?

Fairly sensitive to cycle length... M-F seemed too short while Sa-F seemed perfect.

Is strush repeatable? Is it the same thing here as it was originally?

Workspace theory!

"Building up an accumulated state/perspective/stance"

Drill deeper into positive aspects... Decomposable into different pieces? What is the "satisfaction" feeling?

Is there a "that makes sense" vs "I can use that" distinction?

Need to find non-math examples! Something in personal life or other intellectual pursuits?

Worth exploring the border between ordiation and more explicit processing?

Review ecological perception, esp. affordance and ball catching

Still need to dig into how understanding changes over time... How do I feel about operators now, vs when I started the book, vs at the end? Look for what's coming next!

Can I probe the implicit context/make it explicit? Is there more there?

Under what circumstances do I ordiate? How involuntary is it really?

Ordiation as validation that my "grasp" works? Or just a side-effect/"leaking" through? Do I need to attend to it for it to be useful?
