#+TITLE: 2020-08-13
#+DATE: 2020-08-13
#+CATEGORIES[]: ConSciEnt
#+SUMMARY: Notes from 2020-08-13

Section 7.A exercises - 8.A, excluding exercises. Focused on ordiation and positive components.

- 7.A 1 :: Vague entational restatement of definition of adjoint, felt a need to confirm (missed the feeling itself!)
- 2 :: Entational valusing, set up the equation and switch sides w/conjugate symmetry, seemed perhaps borderline between ordiation and voluntary solving?
- 6 :: Apparent distinction between a "memorized fact" about a basis needing to be orthonormal for the theorem vs actually getting *why*
- 7.31 a :: Ordiated "breaking apart" v into its projection + other component
- 7.36 :: Ordiated commerelial "because T is self adjoint" when the spectral theorem was applied
- 7.39 :: Had to reread several times, finally the formula "slid into" a form of decomposition I recognized

Rescanning sentences until "satisfied", some feeling of (pre-conscious/near-conscious?) "grasp"? Maybe ordiation is a side effect/proof of this when less confident?
