#+TITLE: 2020-08-07 Weekly Review
#+DATE: 2020-08-07
#+CATEGORIES[]: ConSciEnt
#+SUMMARY: Weekly review 2020-08-01 through 2020-08-07
* Observations
Patrodola has differing "intensity"

Some relationship to "calling up"

Baseline state of "pleasant unconfused scanning"

Mental techniques for solving/proving: entational valusing and commerelial conversation/monologue
+ Manipulate formulae
+ Demonstrate some proposition
+ Construct some term

Building up a demonstration sometimes feels like a running narration with "checkpoints" where some subgoal is "done" but can be called up later if needed.

Some kind of entational "example generation" when reading through a section, e.g. division algo for polynomials. Perhaps that one stood out because of how wrong it was?

Some cases instead of fully walking through some technique there's a "shadow" of it. Polynomial division is a guess at this?

Ran out of steam near the end. No expectation of novel insight... But processing notes helped!
* Speculation
"Calling up" is about jumping to techinque... For what? Purpose orientation!

Baseline purposes:
+ Connection to what's interesting/a notion of cool.
+ Solve school problems
+ Notice causal relationships
+ Formal definitions (within math)
+ Identify new patterns/entities

There's a definite difference in how I understand, say, finance (get many of the general concepts and high level dynamics, very little direct hands-on experience) and driving (nearly fully automatic). Does understanding push conscious attention to the "edges"? Free up capacity?

Intimate relationship between understanding and confidence in action

There's a range from basic practical facility to fluency, developing a "style", infering from the patterns of the techniques themselves, etc. Is that reflected in understanding?

Perhaps patrodola is a subtype of a feeling of lack of capability? Testable!

Potential connection with this notion and value of constructive mathematics?

This thinking implies that no applications means no real understanding... If we accept that, perhaps we can explain apparent counterexamples might stem from automatically imagining situations where the knowledge might be used, or an implicit knowledge of how things like this are usually used (esp. classroom!). X to doubt.

Consciousness in general as a "fit for purpose supervisor", or at least as one of its roles? Is "I could confidently use this information in solving typical problem sets" the same kind of feeling as "the ball is in the right part of my visual field for it to end up in my hand"?

Harmony/alignment as pleasurable... Maybe in a certain sense what pleasure *is*? Experienced alignment with organism's survival? Getting way out of scope here, but maybe historical mistakes of "lack of suffering" being the goal confusing the easy confidence with lack of unconfidence/"suffering"?

Example generation as a key test of understanding?

If this model is correct, suggests a stage of understanding where I not only know how to address my use case but I also can generate other likely use cases/have some general confidence in being able to handle unknown ones. Does that feel different? Is that grokking?

"Baseline purposes" list above, esp last three, seems distinct enough from what could be reasonably called immediately goal-directed learning that it's probably worth considering them separate, even if you could stretch it to cover that case.

Some possible "semantics" of patrodola:
+ Don't know what to do for some problem
+ Not able to generate examples
+ Some associative learned pattern of "not enough" grasp on causal structure or identifying things or whatever.
+ Unable to find a place for the idea in the relevant conceptual context

Seems like understanding has a "fullness" dimension... Breadth vs depth?

I seem to have some notion of some kind of causal claim "making sense" or not, possibly related to some aspects of what's discussed here?

Possible practical application/new experimental setting: Applying this notion to teaching others. Hone your ability to notice patrodola and fix it, systematically tackle different categories of understanding.
* Questions/keep in mind
+ What dimensions/degrees of understanding are there?
  + Different kinds? Single purpose vs generating purposes vs unknown purposes?
  + Fullness of application vs confidence in correctness
+ Are there good non-mathematical concepts to drill into?

  Formal definitions being so central is peculiar to math. What is patrodola like elsewhere?
+ What is the relationship between understanding and attention/effort?
+ Any lack-of-ability not really tied to understanding to test?
+ Is there a positive component to the experience of understanding above lack of negative?
+ Am I regularly generating (shadows of?) examples when reading something new?
+ Can I distinguish understanding growth in the different "unguided" understanding cases vs direct purpose orientation?

  Maybe find examples of each to drill down into?
+ Can I distinguish the different semantics of patrodola?

  Are they all real, do they feel different?

  In particular, can I differentiate "what action do I perform next" from other notions?
+ How are these feelings relevant in application?

  Is it just part of the "the path I'm on doesn't need to be modified" gating?
+ What relation do these feelings have to "eureka" moments of insight?
  + Are those reliably generateable?
+ Do different types of uses have different understanding-feelings involved?
+ Have some sense of something like "ready-to-hand" level competence... Attend to this?
+ Look out for causal claims and how I evaluate them
* Action items
+ QFT text for focal topic/purpose ("full ontological accounting")
+ Flesh out peer teaching experiment/put out feelers
+ Figure out balance between enaging with existing work vs exploring new
+ Find neuro lit review approach
+ Find related psych/neuro, esp. EEG
+ Daily/weekly trigger items on project page?
+ Reflect on whether "dimensional" framework is a good way to approach these questions.
