#+TITLE: ConSciEnt

ConSciEnt[fn:name] is my project to develop a naturalistic understanding of consciousness and leverage that to build world-changing technology.

[fn:name] From Consciousness Science Enterprises, pronounced like the English word conscient. I've hardly earned the "science" and have no relevant active "enterprises" to speak of, but I will.

* Philosophy

Consciousness consists of natural biological phenomena that are in principle knowable and exploitable by man.

Unfortunately, the current mainstream scientific paradigm of mechanistic reduction is inadequate to the task, forcing everything to ultimately be explicable in terms of concepts like position, time, mass, etc. that are jointly incapable of even describing conscious experience, let alone including it as a causally relevant phenomenon. With a few important isolated exceptions, all approaches known to me that break out of that mold attempt to dissolve the problem by defining it away or treating it as outside of the realm of scientific inquiry altogether, jumping instead to ungrounded abstract theorizing or outright mysticism. A properly integrated understanding will require a conceptual revolution, but that has happened before within the sciences without abandoning naturalistic empirical inductive reasoning and can happen again.

Consciousness is an evolved biological capability, and any explanations of its nature must ultimately be compatible with evolutionary processes. In particular, any hypotheses of causal intertness or fundamental illusion have an extremely high bar to clear to be considered plausible.

I have direct access to an overwhelming abundance of information about my own experiences, and have ways of intentionally manipulating them. That is enough to incrementally learn about their nature, their causal interrelations, and how they relate to already well-understood natural phenomena. Given the centrality of experience to human flourishing, as my understanding grows there will be opportunities to apply it to practical use, providing both further tools for observation and experimentation and the ultimate proving ground of the correctness of my findings, not to mention financial and other resources to expand the work.

* Approach

I believe we need our [[https://en.wikipedia.org/wiki/Rudolphine_Tables][Rudolphine Tables]] before we attempt our [[https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica][Principia]], and as such am currently focused on extensive observation, phenomenological description, and cataloguing.

My active project is an exploration of the conscious aspects of understanding. What does it feel like to /get/ something, how does that develop, what role does that play in leveraging that understanding for various practical ends? As an initial simple case, I am working my way through mathematical and scientific curricula, pointing ultimately toward a solid understanding of general relativity and the standard model, and observing what I experience as I learn, work through problems, etc. Right now I am reading [[http://linear.axler.net/][Linear Algebra Done Right]], most of whose topics I already know but a good starting point to get into a rhythm of simultaneously learning and observing myself learn.

I keep a regular log of my research notes as a subset of my blog. I am also developing a glossary of etymology-free neologisms that I coin as I make my observations, with the hope of being better able to identify and reason about what I'm noticing without unknowingly smuggling in unjustified assumptions about the role or nature of the aspects of awareness I'm isolating.

As is the nature of open exploration, I expect this approach may wildly change at any moment. I will keep an especially keen eye out for opportunities to get skin in the game by proving out an idea in practice and building a saleable product.

* Following and participating

If you're interested in following along with my progress, please subscribe to my free[fn:free] mailing list where I send out regular updates of what I've been doing, what I've found, and where I'm going next. You can also subscribe to the RSS feed of my blog, either specifically the research log entries or all posts, to get a more up-to-the-minute but perhaps less helpfully structured view. If you want to join in the work in any capacity, please [[mailto:shea@shealevy.com][reach out]]!

[fn:free] For now!
