#+TITLE: ConSciEnt
#+CATEGORIES[]: ConSciEnt
#+SUMMARY: ConSciEnt is my R&D effort to understand consciousness and apply that understanding to build world-changing technology.
#+SUMMARY: ConSciEnt is my project to develop a naturalistic understanding of consciousness and leverage that to build world-changing technology.
#+DATE: 2020-07-30
#+LASTMOD: 2020-08-05
#+LAYOUT: single

ConSciEnt is my R&D effort to understand consciousness and apply that understanding to build world-changing technology.

{{< newsletter >}}

My current active project is /The Texture of Understanding/, where I'm studying the subjective experience associated with having a solid grasp on something, or not, and how that changes as I learn. I'm working my way through a math and physics curriculum that will have me regularly coming up against things I don't understand at all and gradually gain that understanding, and observing my experiences as I go. For more detail and what I've found so far, check out the [[{{< relref "projects/understanding" >}}][project page]]!
* Approach

I am currently generally focused on extensive observation, phenomenological description and cataloguing; I believe we need our [[https://en.wikipedia.org/wiki/Rudolphine_Tables][Rudolphine Tables]] before we attempt our [[https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica][Principia]].

As I work through my individual research projects, I am developing a [[{{< relref "glossary" >}}][glossary]] of etymology-free neologisms that I coin as I make my observations. I am also keeping a regular [[{{< relref "research-notes" >}}][log of my raw research notes]].

I expect this approach may wildly change at any moment. I am especially interested in opportunities to prove out an idea in practice and build a useful product, as well as promising candidates for causally relating aspects of experience to neurobiology.

* Following and participating

If you're interested in following along with my progress, please subscribe below to my free[fn:free] newsletter where I send out updates every Friday on what I've been doing, what I've found, and where I'm going next. You can also subscribe to [[{{< relref path="research-notes" outputFormat="rss" >}}][the RSS feed of my research notes]] or [[{{< relref path="/categories/ConSciEnt" outputFormat="rss" >}}][everything relating to ConSciEnt]] to get a more up-to-the-minute but perhaps less helpfully structured view. If you want to join in the work in any capacity or provide feedback, please [[mailto:shea@shealevy.com][reach out]]!

[fn:free] For now!

* Philosophy

Consciousness consists of natural biological phenomena that are in principle knowable and exploitable by man. It is an evolved biological capability, and any explanations of its nature must ultimately be compatible with evolutionary processes. In particular, any hypotheses suggesting it plays no causal role or some aspect is fundamentally illusory have an extremely high bar to clear to be considered plausible.

I have direct access to an overwhelming abundance of information about my own experiences, and have ways of intentionally manipulating them. That is enough to incrementally learn about their nature, their causal interrelations, and how they relate to already well-understood natural phenomena. Given the centrality of experience to human flourishing, as my understanding grows there will be opportunities to apply it to practical use, providing both further tools for observation and experimentation and the ultimate proving ground of the correctness of my findings, not to mention financial and other resources to expand the work.

The name ConSciEnt (pronounced like the English word "conscient") comes from Consciousness Science Enterprises, aspirationally reflecting both the discovery and application oriented aspects of the approach.

Unfortunately, the current mainstream scientific paradigm of mechanistic reduction, by forcing everything to ultimately be described in terms of concepts like position, time, mass, etc, gets in the way. This set of concepts is incapable of even describing conscious experience, let alone including it as a causally relevant phenomenon. With a few important exceptions, all approaches I now of that break out of that mold attempt to dissolve the problem by defining it away or treating it as outside of the realm of scientific inquiry altogether, jumping instead to ungrounded abstract theorizing or outright mysticism. A properly integrated understanding will require a conceptual revolution, but that has happened before within the sciences without abandoning the empirical inductive approach and it can happen again.
